name: cat_facts_demo
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  hive: ^2.1.0
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.10
  json_serializable: ^6.2.0
  hive_generator: ^1.1.2
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  provider: ^6.0.2
  hive_flutter: ^1.1.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4


flutter:

  uses-material-design: true

